annotator_weight: true
apply_downsampling: true
apply_weights: true
batch_size: 16
data_dir: data
fp16: true
# resume_checkpoint: "output/checkpoints/bert_headtail_fold0.pth"
hidden_size: 768
identity_cols:
- male
- female
- homosexual_gay_or_lesbian
- christian
- jewish
- muslim
- black
- white
- psychiatric_or_mental_illness
- asian
- hindu
- buddhist
- atheist
- bisexual
- transgender
learning_rate: 2.0e-05
max_grad_norm: 1.0
max_length: 128
model_name: bert-base-uncased
model_type: bert_headtail
num_epochs: 3
num_labels: 1
num_workers: 4
output_dir: output
pseudo_label_csv: null
save_checkpoint: true
seed: 42
target_col: target
test_file: test_public_expanded.csv
text_col: comment_text
train_file: train.csv
valid_file: valid.csv
warmup_ratio: 0.1
weight_decay: 0.01
