# LSTM-Capsule model configuration
model_type: "lstm_caps"
model_name: "lstm_caps"

# Data configuration
data_dir: "data"
train_file: "train_folds.csv"
valid_file: "valid.csv"
test_file: "test_public_expanded.csv"
text_col: "comment_text"
target_col: "target"
identity_cols:
  - "male"
  - "female"
  - "homosexual_gay_or_lesbian"
  - "christian"
  - "jewish"
  - "muslim"
  - "black"
  - "white"
  - "psychiatric_or_mental_illness"
  - "asian"
  - "hindu"
  - "buddhist"
  - "atheist"
  - "bisexual"
  - "transgender"

# Model parameters
vocab_size: 50000
embedding_dim: 300
hidden_dim: 128
num_layers: 2
dropout: 0.2
capsule_dim: 8
num_capsules: 10
pretrained_embeddings: True
embedding_path: "data/embeddings/glove.840B.300d.txt"

# Training parameters
batch_size: 64
max_length: 256
num_epochs: 5
learning_rate: 2.0e-3
weight_decay: 1.0e-5
warmup_ratio: 0.1
max_grad_norm: 1.0
apply_downsampling: True
apply_weights: True
annotator_weight: True
pseudo_label_csv: null
num_workers: 4

# Output configuration
output_dir: "output"
save_checkpoint: True

# Random seed
seed: 42 