name: Deep Fairness CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      HF_HOME: ${{ runner.temp }}/hf-cache
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Cache HF models
      uses: actions/cache@v4
      with:
        path: ${{ env.HF_HOME }}
        key: hf-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install PyTorch CPU version to speed up CI
        pip install -r requirements.txt
        pip install pytest
        
    - name: Dry run training
      run: |
        python -m src.train --model bert_headtail --dry_run
        
    - name: Pseudo-label dry-run
      run: |
        python scripts/pseudo_label.py --base-model bert_headtail --unlabeled-csv data/train.csv --out-csv /tmp/pseudo.csv --dry-run
        
    - name: Dry run training with pseudo-labels
      run: |
        python -m src.train --model bert_headtail --pseudo-label-csv /tmp/pseudo.csv --dry-run
        
    - name: Dry run prediction
      run: |
        python -m src.predict --model bert_headtail --dry-run
        
    - name: Generate metrics
      run: |
        python scripts/write_metrics.py --predictions output/preds/bert_headtail.csv
        
    - name: Run tests
      run: |
        pytest
        
    - name: Make figures-fast
      run: |
        make figures-fast
        
    - name: Upload figures as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: fairness-figures
        path: figs/
        
    - name: Upload metrics as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: fairness-metrics
        path: results/ 